# Generated by Django 4.2.7 on 2025-04-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_logo',
            field=models.ImageField(blank=True, default='download.jpg', null=True, upload_to='static/images'),
        ),
    ]
