# Generated by Django 4.2.7 on 2025-04-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0002_job_job_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
