# Generated by Django 5.1.1 on 2025-04-08 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0003_job_company_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job_application',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='job_seekers.job'),
        ),
    ]
