# Generated by Django 5.1.1 on 2025-04-10 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0004_alter_job_company_details_alter_job_application_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_applied', to=settings.AUTH_USER_MODEL),
        ),
    ]
