# Generated by Django 5.1.1 on 2025-04-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0006_alter_profile_profile_picture_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='CV',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
