# Generated by Django 4.2.7 on 2025-05-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer_account',
            name='company_logo',
            field=models.ImageField(blank=True, default='download.jpg', null=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_logo',
            field=models.ImageField(blank=True, default='download.jpg', null=True, upload_to='static/images'),
        ),
    ]
