# Generated by Django 5.1.1 on 2025-04-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0009_alter_customuser_role_alter_job_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='employer',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('employer', 'Employer')], max_length=30),
        ),
    ]
